version: '3.8'
services:

  es-node1:
    image: elasticsearch:8.15.0
    container_name: es-node1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
      - xpack.watcher.enabled=false
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - evm-history-es-data1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -XGET 'http://localhost:9200/_cluster/health?pretty' | grep status | grep -q '\\(green\\|yellow\\)'"
        ]
      interval: 10s
      timeout: 10s
      retries: 30
    networks:
      - evm-history-net

  kibana-node1:
    image: kibana:8.15.0
    container_name: kibana-node1
    depends_on:
      es-node1:
        condition: service_healthy
    volumes:
      - evm-history-kibana-node1:/usr/share/kibana/data
      - ./dashboard.ndjson:/usr/share/kibana/config/dashboard.ndjson
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: '["http://es-node1:9200"]'
    working_dir: /usr/share/kibana/config
    healthcheck:
      test: curl -s -XPOST 'localhost:5601/api/saved_objects/_import?overwrite=true' -H 'kbn-xsrf:true' --form file=@dashboard.ndjson >/dev/null || exit 1
      interval: 10s
      timeout: 10s
      retries: 30
    networks:
      - evm-history-net

volumes:
  evm-history-es-data1:
  evm-history-kibana-node1:

networks:
  evm-history-net:
